### ISSUE TITLE
Write a BOM for the CSV file, so Excel opens it with correct encoding

### ISSUE THREAD

**Issue by tharban** [seanstaley/database-query-plugin#33]
You could write a BOM '\ufeff' as first byte instead of just copying over the String to the output. That way Excel recognizes the encoding (starting with Excel2007) and a mere Excel user can cope with this way easier.

On the other hand: This should only be used by people who can wield the Excel axe wisely.

**Comment by seanstaley** [comment]
Will backport your fix to the 2.0 I am working to release soon.

Thanks for the help!
